doktorzy = ["Pierwszy", "Drugi", "Trzeci", "Czwarty", "Piąty", "Szósty", "Siódmy", "Ósmy", "Dziewiąty", "Dziesiąty",
            "Jedenasty","Dwunasty","Trzynasty"]
towarzysze = [
    "Barbara Wright",
    "Ben Jackson",
    "Dodo Chaplet",
    "Ian Chesterton",
    "Katarina",
    "Polly Wright",
    "Sara Kingdom",
    "Steven Taylor",
    "Susan",
    "Vicki Pallister",
    "Archibald Hamish Lethbridge-Stewart",
    "Bill Potts",
    "Bret Vyon",
    "Tegan Jovanka",
    "Dot, Harroll and Jack Strong",
    "Robert Zierath",
    "Amy and Tony Barker",
    "Butch",
    "Chertzog",
    "Hill",
    "Alan, George, Helen and Ida Mortimer",
    "Shelly",
    "Badger",
    "Rebecca Nurse",
    "John Who",
    "Gillian Who",
    "Oliver Harper",
    "Mickey Smith",
    "Jack Harkness",
    "River Song",
    "Jo Grant",
    "Porridge",
    "Brigadier",
    "Jamie McCrimmon",
    "Victoria Waterfield",
    "Zoe Heriot",
    "Marmaduke",
    "Serena",
    "John Benton",
    "Liz Shaw",
    "Sarah Jane Smith",
    "Mike Yates",
    "Arnold",
    "Brod",
    "Charlie Fisher",
    "Finney",
    "Lammers",
    "Nick Willard",
    "Jeremy Fitzoliver",
    "Joshua Douglas",
    "Adric",
    "The Brigadier",
    "Harry Sullivan",
    "K9 Mark I",
    "K9 Mark II",
    "Leela",
    "Nyssa",
    "Romana I",
    "Romana II",
    "Spandrell",
    "K9 Mark III",
    "Oliver Day",
    "Unnamed companion",
    "Bryony Mailer",
    "Figment",
    "Milena",
    "Putta Pattershaun 5",
    "Sharon Davies",
    "Tiger Maratha",
    "Andric",
    "Joan Brown",
    "Miss Young",
    "Morris",
    "Vesuvius",
    "Ivan Asimoff",
    "Margaret Hopwood",
    "Ann Kelso",
    "Fenella Wibbsey",
    "Naomi Cross",
    "Mervyn Peake",
    "Turlough",
    "Kamelion",
    "Peri Brown",
    "Business woman",
    "Will Chandler",
    "Jane Hampden",
    "Sir Justin",
    "Shayde",
    "Maxwell Edison",
    "Gus Goodman",
    "Robert McIntosh",
    "Thomas Brewster",
    "Hannah Bartholemew",
    "Erimem",
    "Amy",
    "Alayna",
    "Brooke 1",
    "Melanie Bush",
    "Grant Markham",
    "Emily Chaudhry",
    "Will Hoffman",
    "William",
    "Flora Millrace",
    "Frobisher",
    "Actis",
    "Evelyn Smythe",
    "Charlotte Pollard",
    "Mila",
    "Flip Jackson",
    "Henry Gordon Jago",
    "George Litefoot",
    "Constance Clarke",
    "Heather Threadstone",
    "Hebe Harrison",
    "Patricia McBride",
    "Jason",
    "Crystal",
    "Zog",
    "Splinx",
    "Rex",
    "Ace",
    "K9",
    "Bernice Summerfield",
    "Chris Cwej",
    "Roz Forrester",
    "Wolsey",
    "Tramp",
    "Catherine Broome",
    "Ruby Duvall",
    "Private",
    "Olla",
    "Ly-Chee",
    "Bev Tarrant",
    "Hex",
    "Elizabeth Klein",
    "Raine Creevy",
    "Sally Morgan",
    "Lysandra Aristedes",
    "Will Arrowsmith",
    "Mags",
    "Rachel Cooper",
    "Jemima",
    "Panda",
    "Grace Holloway",
    "Chang Lee",
    "Sam Jones",
    "Fitz Kreiner",
    "Compassion",
    "Anji Kapoor",
    "Trix MacMillan",
    "Izzy Sinclair",
    "Charley Pollard",
    "C'rizz",
    "Bazima",
    "Lucie Miller",
    "Edward Fyne",
    "Evelyn Chan",
    "Ayfai",
    "Iris Wildthyme",
    "Miranda Dawkins",
    "Lorenzo Smitt",
    "Debbie Castle",
    "Stacy Townsend",
    "Ssard",
    "Kroton",
    "Destrii",
    "Josie Day",
    "Billy Wilkins",
    "Ray Stobbs",
    "Ediphis",
    "Chantir",
    "Fey Truscott-Sade",
    "Gemma and Samson Griffin",
    "Mary Shelley",
    "Guy",
    "Tamsin Drew",
    "Molly O'Sullivan",
    "Liv Chenka",
    "Helen Sinclair",
    "The Eleven",
    "Tania Bell",
    "Andy Davidson",
    "Bliss",
    "Alex Campbell",
    "Cass Fermazzi",
    "Sarana Teel",
    "Susan Foreman",
    "Daphne",
    "Ria",
    "Sheena",
    "Cinder",
    "Petrella",
    "The Squire",
    "War Child Master",
    "Rejoice",
    "War Ollistra",
    "Heleyna",
    "Kalan",
    "Case",
    "Asmuth",
    "Eleventh General",
    "Rose Tyler",
    "Adam Mitchell",
    "Lynda Moss",
    "Ali",
    "Tara Mishra",
    "Nova",
    "Audrey Mohinson",
    "Brigadier Alistair Gordon Lethbridge-Stewart",
    "Donna Noble",
    "Martha Jones",
    "K9 MKIII",
    "Astrid Peth",
    "Jenny",
    "Lady Christina de Souza",
    "Cassie Rice",
    "Jimmy Stalkingwolf",
    "Wilfred Mott",
    "Jackie Tyler",
    "Rosita Farisi",
    "Jackson Lake",
    "Adelaide Brooke",
    "Gisella",
    "Alsa",
    "Nikki Jupiter",
    "Rok Ma",
    "June",
    "Koral",
    "Jon Bowman",
    "Jake and Vienna Carstairs",
    "Wallace Fitch",
    "Emily Parr",
    "Kate Maguire",
    "Mai Kondo",
    "Christina de Souza 2.0",
    "Peter Cushing",
    "Majenta Pryce",
    "Heather McCrimmon",
    "Wolfie Ryter",
    "Jayne Kadett",
    "Matthew Finnegan",
    "Emily Winter",
    "Gabby Gonzalez",
    "Rose-the-cat",
    "Cindy Wu",
    "Alistair Gordon Lethbridge-Stewart",
    "Grayla",
    "Anya Kingdom",
    "Mark Seven",
    "Sugar MacAuley",
    "Amy Pond",
    "Rory Williams",
    "Craig Owens",
    "Kazran Sardick",
    "Winston Churchill",
    "Brian Williams",
    "Clara Oswald",
    "Canton Everett Delaware III",
    "Angie and Artie Maitland",
    "Abigail Pettigrew",
    "Nefertiti",
    "John Riddell",
    "Handles",
    "Jenibeth, Sabel and Ollus Blakely",
    "Olga Bordmann",
    "Theol Willoughby",
    "Kevin",
    "Decky Flamboon",
    "Alice Obiefune",
    "John Jones",
    "Amy Johnson",
    "ARC",
    "Abslom Daak",
    "The Sapling",
    "Edward Anderson",
    "Christina de Souza",
    "Ally",
    "Valarie Lockwood",
    "Alice Watson",
    "Nardole",
    "Courtney Woods",
    "Rigsy",
    "Bors",
    "Missy",
    "Fifty-one",
    "Ceri",
    "Peter Summerfield",
    "Ruth Leonidas",
    "Jack McSpringheel",
    "CJ Finch",
    "Hattie Munroe",
    "Jess Collins",
    "Maxwell Collins",
    "Jata",
    "Sonny",
    "Athena",
    "Lloyd Collins",
    "Devina Collins",
    "Estrella",
    "George V",
    "Eliza Jones",
    "Jain Relph",
    "Heddy Garber",
    "Julie d'Aubigny",
    "Gaz",
    "Gertie",
    "Sonny Robinson",
    "Val Kent",
    "Grant",
    "Lucy Fletcher",
    "Jennifer Fletcher",
    "Alex Yow",
    "Brandon Yow",
    "Keira Sanstrom",
    "Danny Pink",
    "Petronella Osgood",
    "Yasmin Khan",
    "Ryan Sinclair",
    "Graham O'Brien",
    "Dan Lewis",
    "Ada Lovelace",
    "Noor Inayat Khan",
    "Grace O'Brien",
    "Lizzie",
    "Dorothy"
]
przeciwnicy = [
    "Abaddon (Torchwood)",
    "Abzorbaloff",
    "Acomat",
    "Adam Mitchell",
    "Adam Smith",
    "Adipose",
    "Adolf Hitler (Doctor Who)",
    "Akhaten",
    "Alaya",
    "Alex Hopkins",
    "Aliens (Doctor Who)",
    "Ancient Lights",
    "Androvax",
    "Animus (Doctor Who)",
    "Anne Droid",
    "Antibodies",
    "Arcturus",
    "Ascaris",
    "Ashad",
    "Asquith Slitheen",
    "Autons",
    "Axons",
    "Axos",
    "Azal (Doctor Who)",
    "Azure",
    "Baltazar",
    "Bane Mother",
    "Bannermen",
    "Bartle",
    "Beaus",
    "Beep the Meep",
    "Belazs",
    "Bert Walker",
    "Black Guardian",
    "Blathereen Family",
    "Blon Fel-Fotch Passameer-Day Slitheen",
    "Bloorm Vungah Bart Slitheen",
    "Boneless (Doctor Who)",
    "Bonnie (Doctor Who)",
    "Borusa",
    "BOSS",
    "Bragen",
    "Brigade Leader Lethbridge Stewart",
    "Broton",
    "Bruno Taltalian",
    "Brynblaidd Cannibals",
    "Bus Conductor",
    "Butler (Doctor Who)",
    "Captain Blade",
    "Captain Cook",
    "Captain Dent",
    "Captain Hardaker",
    "Captain John Hart",
    "Captain of Zanak",
    "Captain Pike",
    "Captain Rorvik",
    "Captain Wrack",
    "Carrionites",
    "Carys Fletcher (Torchwood)",
    "Catherine de Medici (Doctor Who)",
    "Celation",
    "Celestial Toymaker",
    "Centurion (Doctor Who)",
    "Cessair of Diplos",
    "Chameleons (Doctor Who)",
    "Channing (Doctor Who)",
    "Charles Grover",
    "Charlie Duffy",
    "Cherub",
    "Chessene",
    "Chief Caretaker",
    "Chief Clown",
    "Chief Officer",
    "Chief Scientist",
    "Chief Sea Devil",
    "Childeric",
    "Chris Slitheen",
    "Clockwork Repair Droids",
    "Colonel Manton",
    "Colony Sarff",
    "Commander Kaagh",
    "Commander Millington",
    "Commander Skorr",
    "Commander Stark",
    "Count Grendel",
    "Crozier",
    "Cult of Skaro",
    "Cyber Controller",
    "Cyber Planner",
    "Cyber-Leader",
    "CyberKing",
    "CyberMasters",
    "Cybermats",
    "Cybermen",
    "Dalek Antibodies",
    "Dalek Caan",
    "Dalek Emperor",
    "Dalek Jast",
    "Dalek Prime Minister",
    "Dalek Sec",
    "Dalek Thay",
    "Dalek Time Controller",
    "Dalek Time Strategist",
    "Daleks",
    "Daniel Barton",
    "Davey",
    "Davros",
    "Dax Fex Fize Slitheen",
    "De Flores",
    "Didius",
    "Doland",
    "Dominators (Doctor Who)",
    "Drathro",
    "Drax (Doctor Who)",
    "Dream Lord",
    "Dregs",
    "Eckersley",
    "Ed Morgan",
    "Eddie Connolly",
    "Eelek",
    "El Akir",
    "Eldrad",
    "Emojibots",
    "Empress of the Racnoss",
    "Enlightenment",
    "Eric Klieg",
    "Eric Stahlman",
    "Ettis",
    "Eugene Tacitus",
    "F",
    "Faction Paradox",
    "Fadros Pallujikaa",
    "Fairies (Torchwood)",
    "Family of Blood",
    "Father Angelo",
    "Fearmonger (Doctor Who)",
    "Fendahl",
    "Fenric",
    "Flemming",
    "Flesh Moths",
    "Florence Finnegan",
    "Florm Rox Fey Fenerill-Slam Slitheen",
    "Forester",
    "Francesco (Doctor Who)",
    "Frax (Doctor Who)",
    "Futurekind",
    "Gagan Rassmussen",
    "Ganymede Systems",
    "Garvin",
    "Gavrok",
    "Gearon",
    "Gelth",
    "General Carrington",
    "General Cobb",
    "General Finch",
    "General Staal",
    "George Cranleigh",
    "George Ratcliffe",
    "Glune Fex Fize Sharlaveer-Slam Slitheen",
    "Gods of Ragnarok",
    "Gorgon (Doctor Who)",
    "Goth (Doctor Who)",
    "Graff Vynda-K",
    "Grand Marshal Skaldak",
    "Grand Serpent",
    "Grandfather Paradox",
    "Gray (Torchwood)",
    "Great Vampire",
    "Gundans",
    "Half Face Man",
    "Harrison Chase",
    "Harry Mailer",
    "Harry Slocum",
    "Hawthorne",
    "Heavenly Hosts",
    "Hedin",
    "Helen A",
    "Henry Van Statten",
    "Hepesh",
    "Hetocumtek",
    "High Priest Clovis",
    "Hinks",
    "House (Doctor Who)",
    "Ice Governess",
    "Ice Warriors",
    "Icthar",
    "Irongron",
    "Ixta",
    "Jagrafess",
    "Jocelyn Stevens",
    "Jocrassa Fel-Fotch Passameer-Day Slitheen",
    "John Benton (Parallel Universe)",
    "John Bromley",
    "John Lumic",
    "Joinson Dastari",
    "Joshua Naismith",
    "Josiah Samuel Smith",
    "Judoon",
    "Julius Grayle",
    "K1 Robot",
    "Kaftan",
    "Kahler-Jex",
    "Kal (Doctor Who)",
    "Kalik",
    "Kandy Man",
    "Kane (Doctor Who)",
    "Kantorfarri",
    "Kara (Doctor Who)",
    "Karl (Doctor Who)",
    "Kasaavin",
    "Keillor",
    "Kelner",
    "Kess",
    "King Hydroflax",
    "King Richard III (Doctor Who)",
    "Kist Magg Thek Lutiven-Day Slitheen",
    "Kiston",
    "Klineman Halpen",
    "Koquillion",
    "Korst Gogg Thek Lutiven-Day Slitheen",
    "Kracauer",
    "Krang (Doctor Who)",
    "Krasko",
    "Krillitanes",
    "Kroagnon",
    "Kroll",
    "Krotons",
    "Krynoids",
    "Lady Adrasta",
    "Lady Cassandra O'Brien.Δ17",
    "Lady Peinforte",
    "Leandro",
    "Leef Apple Glyn Slitheen-Blathereen",
    "Li H'sen Chang",
    "Lieutenant Koenig",
    "Light",
    "Lilith (Doctor Who)",
    "Linx",
    "Livilla",
    "Lobos",
    "Locusta",
    "Lord Azaxyr",
    "Lord Kiv",
    "Lord Slaar",
    "Lord Sutcliffe",
    "Lucius Petrus Dextrus",
    "Luke Rattigan",
    "Lupton",
    "Lytton",
    "Maaga",
    "Macra",
    "Madame Kovarian",
    "Magnus Greel",
    "Malpha",
    "Mandragora Helix",
    "Manish (Doctor Who)",
    "Mara (Doctor Who)",
    "Mark Lynch",
    "Marshal of Solos",
    "Marshal Tavannes",
    "Marsissus",
    "Martin Trueman",
    "Mary (Torchwood)",
    "Master Brain",
    "Master of the Land of Fiction",
    "Matron Casp",
    "Matron Cofelia",
    "Matrona",
    "Maurice Caven",
    "Mavic Chen",
    "Max Capricorn",
    "Medusa (Doctor Who)",
    "Meglos",
    "Melanicus",
    "Mentors",
    "Mercy Hartigan",
    "Mestor",
    "Metaltron",
    "Metebelis Spiders",
    "Mickey Auton",
    "Midnight Entity",
    "Mike Smith",
    "Mike Yates",
    "Minotaur (Doctor Who)",
    "Missy (Doctor Who)",
    "Mona Lisa (The Sarah Jane Adventures)",
    "Monarch (Doctor Who)",
    "Monoid One",
    "Monoids",
    "Morax",
    "Morbius (Doctor Who)",
    "Mordred (Doctor Who)",
    "Morgaine",
    "Morgan (Doctor Who)",
    "Morgana (Doctor Who)",
    "Morgus",
    "Morka",
    "Moroks",
    "Movellans",
    "Mr. Diagoras",
    "Mr. Finch",
    "Mr. Magpie",
    "Mr. Seyton",
    "Mr. Sin",
    "Mr. Smith (Sarah Jane Adventures)",
    "Mr. Webber",
    "Mummy (Doctor Who)",
    "Nephew",
    "Nestene Consciousness",
    "Nicholas Valentine",
    "Nobody No-One",
    "Noma",
    "Notsussybaka900",
    "Nyder",
    "Oak (Doctor Who)",
    "Ogrons",
    "Omega (Doctor Who)",
    "Order of St. Agnes",
    "Orum",
    "Oswald Danes",
    "Packer",
    "Paul Hunt",
    "Peg Dolls",
    "Persuasion",
    "Primords",
    "Prisoner Zero",
    "Private Wyatt",
    "Professor Whitaker",
    "Professor Zaroff",
    "Pting",
    "Quantum Archangel",
    "Quillam",
    "Rago (Doctor Who)",
    "Rahnius Slitheen",
    "Rakaya",
    "Ramón Salamander",
    "Rassilon",
    "Raston Warrior Robot",
    "Reconnaissance Dalek",
    "Reegan",
    "Republican Security Forces",
    "Restac",
    "Rex Farrel",
    "Richard Lazarus",
    "Richard Maynarde",
    "Ringmaster (Doctor Who)",
    "Ringway",
    "Rintan",
    "Roboforms",
    "Robot Knights",
    "Robot Yeti",
    "Rogue Angel",
    "Rosanna Calvierri",
    "Rudge",
    "Rupesh Patanjali",
    "Rusty (Doctor Who)",
    "Rutans",
    "Sauvix",
    "Scarecrows (Doctor Who)",
    "Scaroth",
    "Scibus",
    "Sea Devils",
    "Seb (Doctor Who)",
    "Security Chief",
    "Sentreal",
    "Sentris",
    "Sevcheria",
    "Shadow (Doctor Who)",
    "Sharaz Jek",
    "Sheriff of Nottingham (Doctor Who)",
    "Shoal of the Winter Harmony",
    "Shockeye",
    "Sil (Doctor Who)",
    "Silents",
    "Silurians",
    "Sip Fel-Fotch Passameer-Day Slitheen",
    "Sir George Hutchinson",
    "Sir James Quinlan",
    "Sisters of Plenitude",
    "Dr. Skagra",
    "Skovox Blitzer",
    "Slitheen Family",
    "Slitheen-Blathereen",
    "Smilers",
    "Smythe (Doctor Who)",
    "SniperBot",
    "Solana Mercurio",
    "Solicitor Grey",
    "Solis",
    "Solomon (Doctor Who)",
    "Solomon's Robots",
    "Sontarans",
    "Special Weapon Dalek",
    "Sskel",
    "Stike",
    "Stor",
    "Stotz",
    "Styggron",
    "Styre",
    "Supreme Dalek",
    "Supreme Dalek (New Dalek Paradigm)",
    "Supreme One",
    "Sutekh (Doctor Who)",
    "Suzie Costello",
    "Swarm (Doctor Who)",
    "Sycorax (Doctor Who)",
    "Tarpok",
    "Tecteun",
    "Tegana",
    "Tekker",
    "Terileptil Android",
    "Terileptils",
    "Tharils",
    "Thawn",
    "The Beast (Doctor Who)",
    "The Borad",
    "The Brethren (Doctor Who)",
    "The Child (Doctor Who)",
    "The Collector (Doctor Who)",
    "The Destroyer",
    "The Division",
    "The Editor",
    "The Eleven",
    "The Empty Child",
    "The Enemy (Doctor Who)",
    "The Figure",
    "The Fisher King (Doctor Who)",
    "The Flood (Doctor Who)",
    "The Foretold",
    "The Gravis",
    "The Great Intelligence",
    "The Gunslinger (Doctor Who)",
    "The Hath",
    "The Host",
    "The Malus",
    "The Master (Child)",
    "The Master (Classic Who)",
    "The Master (Doctor Who)",
    "The Master (Harold Saxon)",
    "The Master (O)",
    "The Master (Yana)",
    "The Meddling Monk",
    "The Myrka",
    "The Oracle (Doctor Who)",
    "The Rani",
    "The Skarasen",
    "The Three Families",
    "The Trickster (The Sarah Jane Adventures)",
    "The Valeyard",
    "The War Chief",
    "The War Lord",
    "The Wire",
    "Theodore Maxtible",
    "Tia Karim",
    "Time Beetle",
    "Time Lord Victorious",
    "Time Zombies",
    "Tlotoxl",
    "Toba",
    "Tobias Vaughn",
    "Toclafane",
    "Tonila",
    "Tractators",
    "Trantis",
    "Trask (Doctor Who)",
    "Tree Lorn Acre Slitheen-Blathereen",
    "Turoc",
    "Tzim-Sha",
    "Urak",
    "Vardans",
    "Varga (Doctor Who)",
    "Varl",
    "Vashta Nerada",
    "Vervoids",
    "Vespiform",
    "Vigil",
    "Virus of the Purpose",
    "Von Weich",
    "Warrien",
    "Weed Creature",
    "Weeping Angels",
    "Whisper Men",
    "Winifred Gillyflower",
    "Wirrn",
    "WOTAN",
    "Yartek",
    "Zagreus",
    "Zephon (Doctor Who)",
    "Zondal",
    "Zu-Zana",
    "Zygons"
]